/*
 * OpenRemote, the Home of the Digital Home.
 * Copyright 2008-2011, OpenRemote Inc.
 *
 * See the contributors.txt file in the distribution for a
 * full listing of individual contributors.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package org.openremote.controller.model.event

global org.openremote.controller.statuscache.CommandFacade execute;


rule "Execute on three-way switch ON"

when

  Switch( source == "sensor 1", value == "on")
  Switch( source == "sensor 2", value == "on")
  Switch( source == "sensor 3", value == "on")

then

  execute.command("counter", "all on");

end


rule "Execute on three-way switch OFF"

when

  Switch( source == "sensor 1", value == "off")
  Switch( source == "sensor 2", value == "off")
  Switch( source == "sensor 3", value == "off")

then

  execute.command("counter", "all off");

end
