/*
 * OpenRemote, the Home of the Digital Home.
 * Copyright 2008-2011, OpenRemote Inc.
 *
 * See the contributors.txt file in the distribution for a
 * full listing of individual contributors.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package org.openremote.controller.model.event

global org.openremote.controller.statuscache.SwitchFacade switches;

rule "Turn Switch On"

when

  Switch( source == "switch444", value == "off" )

then

  switches.name("switch444").on();

end


/* This rule should be executed as a result of the first one going off... */

rule "Turn switch off, with value 'closed'"

when

  Switch (sourceID == 444, value == "on", $name : source)

then

  switches.name($name).off("closed");

end


/* This rule is next in chain, triggered by the switch state change in above rule */

rule "Turn switch on, with value 'Complete'"

when

  Switch (sourceID == 444, value == "closed", $name : source)

then

  switches.name($name).on("Complete");

end

